#=====================
#
# Serene Python Client configuration for constraint programming (CP) solver
#
#=====================

# This is the path to the chuffed CP solver; do not add / at the end
chuffed-path: /home/natalia/PycharmProjects/serene-python-client/stp/minizinc/chuffed_20170525

# This is the path to the model.mzn
model-path: /home/natalia/PycharmProjects/serene-python-client/stp/minizinc/model.mzn

# This is the path to MiniZinc where mzn2fzn is located
mzn2fzn-exec: /home/natalia/Installs/MiniZincIDE-2.1.4-bundle-linux-x86_64/mzn2fzn

# This is the path to MiniZinc where solnsout is located
solns2out-exec: /home/natalia/Installs/MiniZincIDE-2.1.4-bundle-linux-x86_64/solns2out

# Timeout for the solver
timeout: 10